version: "3.8"
services:
  tiktok-bot:
    build: .
    env_file: .env
    volumes:
      - /tmp:/tmp
      - ./data:/app/data
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 8.8.8.8
