version: "3.8"

services:
  tiktok-bot:
    build: .
    env_file: .env
    environment:
      - VLESS_URL=${VLESS_URL}
    volumes:
      - /tmp:/tmp # временные файлы для видео/картинок
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
