services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "''", "--appendonly", "no"]
    networks: [app]
    restart: unless-stopped

  xray:
    image: teddysun/xray
    container_name: xray-vless
    volumes:
      - ./xray/config.json:/etc/xray/config.json:ro
    ports:
      - "127.0.0.1:1080:1080"   # SOCKS5 (локально)
      - "127.0.0.1:1087:1087"   # HTTP proxy (локально)
    networks: [app]
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_URL: redis://redis:6379
      QUEUE_NAME: tiktok
      # Проксируем ВСЁ через Xray
      HTTP_PROXY:  http://xray:1087
      HTTPS_PROXY: http://xray:1087
      ALL_PROXY:   socks5h://xray:1080
      NO_PROXY: "127.0.0.1,localhost,redis"
      DASHBOARD_BASIC_AUTH: ${DASHBOARD_BASIC_AUTH:-admin:admin}
      SIZE_LIMIT_MB: "50"
    depends_on: [redis, xray]
    networks: [app]
    restart: unless-stopped
    ports:
      - "53500:3000"
    volumes:
      - bot_data:/app/data
    dns:
      - 8.8.8.8
      - 1.1.1.1

  worker:
    build: ./worker
    environment:
      REDIS_URL: redis://redis:6379
      QUEUE_NAME: tiktok
      TELEGRAM_BOT_TOKEN: ${BOT_TOKEN}
      SIZE_LIMIT_MB: "50"
      MAX_CONCURRENCY: "2"
      # Прокси для ytdlp/ffmpeg/любых http-клиентов
      HTTP_PROXY:  http://xray:1087
      HTTPS_PROXY: http://xray:1087
      ALL_PROXY:   socks5h://xray:1080
      NO_PROXY: "127.0.0.1,localhost,redis"
      # Прямо передаём в yt-dlp:
      YTDLP_PROXY: http://xray:1087
    volumes:
      - tmp_data:/tmp/downloads
    depends_on: [redis, xray]
    networks: [app]
    restart: unless-stopped

networks:
  app:

volumes:
  tmp_data:
  bot_data:
